# Generated by Django 2.2.4 on 2020-05-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0002_auto_20190824_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='tweet_pics', verbose_name=''),
        ),
    ]
